### ISSUE TITLE
Make the precision default to 3 on the motor record fields

### ISSUE THREAD

**Issue by canismarko** [spc-group/ioc-austin#15]

**Comment by canismarko** [comment]
This is complete in caproto-apps. We'll need to re-factor the status.py file to use the caprotoapps motor records. We have some decisions to make, though, regarding how the motor speed relates to the overall speed of the robot. @yannachen we can talk after the break?

**Comment by yannachen** [comment]
Sure. I will be back on 1/8. Happy new year!Sent from my iPhoneOn Dec 31, 2023, at 14:49, Mark Wolfman ***@***.***> wrote:﻿
This is complete in caproto-apps. We'll need to re-factor the status.py file to use the caprotoapps motor records. We have some decisions to make, though, regarding how the motor speed relates to the overall speed of the robot. @yannachen we can talk after the break?

**Comment by canismarko** [comment]
Converted the motor support over to caproto-apps, which solved the precision problem.

Fixed: a9de5cdb93b7d437502dc6133ba20b3d09d559ae
